import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '../styles/globals.scss';

// import localFont from 'next/font/local'
// const avenirFont = localFont({
//   src: [
//     {
//       path: '../public/fonts/AvenirLTStd-Roman.woff2',
//       weight: '400',
//       style: 'normal',
//     },
//   ]
// })

// import Header from '@/components/header/Header';

const montserrat = Montserrat({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        {/* <Header /> */}
        {children}
      </body>
    </html>
  );
}
