import type { Metadata } from 'next';
import { ReactLenis } from 'lenis/react';
import '../styles/globals.scss';
// import { ViewTransitions } from 'next-view-transitions';
import Header from '@/components/header/Header';
import { Providers } from './providers';

import localFont from 'next/font/local';
const terminaFont = localFont({
  variable: '--font-primary',
  preload: true,
  src: [
    {
      path: '../public/fonts/Termina-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Termina-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/Termina-Demi.woff2',
      weight: '600',
      style: 'normal',
    },
  ],
});
// import { Montserrat } from 'next/font/google';
// const montserrat = Montserrat({
//   subsets: ['latin'],
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={`${terminaFont.className}`}>
          <ReactLenis root>
            <Header />
            {children}
          </ReactLenis>
        </body>
      </html>
    </Providers>
  );
}
